name: Build & Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup npmrc for github publishing
        uses: actions/setup-node@v1
        with:
          node-version: 14.9.x
          registry-url: https://npm.pkg.github.com/
          scope: '@RFL-NFTPlatform'
      - name: Install NPM Modules
        run: npm install
      - name: Build
        run: npm run build
      - name: Add Name Scope
        run: npm run addscope
      - name: Publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
